DESCRIPTIVE_FILTERS = {
    "price_min": 10.0,
    "price_max": 1000.0,
    "avg_daily_volume_min": 2_500_000,
    "avg_dollar_volume_min": 50_000_000,
    "market_cap_min": 500_000_000,
    "market_cap_max": None,
    "float_shares_min_millions": 5.0,
    "float_shares_max_millions": 2_000.0,
    "optionable_only": True,
    "shortable_only": False,
    "exclude_etfs": False,
    "sector_allowlist": [],
    "ticker_blacklist": [],
    "country_allowlist": ["US"],
    "max_spread_pct": 0.75,
}
